spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.market.domain;
  config-location: classpath:/mybatis/mybatis-config.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
logging:
  config: classpath:logback-spring.xml